#Endless Forest

[colors]
  # Default colors
  [colors.primary]
  background = '0x2b3339'
  foreground = '0xd3c6aa'

  # Normal colors
  [colors.normal]
  black = '0x2b3339'
  red = '0xe67e80'
  green = '0xa7c080'
  yellow = '0xdbbc7f'
  blue = '0x7fbbb3'
  magenta = '0xd699b6'
  cyan = '0x83c092'
  white = '0xd3c6aa'

  # Bright colors
  [colors.bright]
  black = '0x7e837f'
  red = '0xe67e80'
  green = '0xa7c080'
  yellow = '0xdbbc7f'
  blue = '0x7fbbb3'
  magenta = '0xd699b6'
  cyan = '0x83c092'
  white = '0xf2e5bc'
